version: '3'

services:
  cpx_120:
    image: store/citrix/netscalercpx:12.0-56.20
    ports:
      - '9080:80'
      - '443:443'
    environment:
      EULA: 'yes'
      PLATFORM: 'CP1000'
    privileged: true
    networks:
      my-network:
        ipv4_address: 172.20.0.4

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
