- hosts: citrix_adc
  gather_facts: no
  vars:
    resource: lbvserver
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6
  collections:
    - citrix.adc


  tasks:
    - name: Do mas login
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: login

      register: result

    - name: Print result

      debug:
        msg: "result {{ result }}"

    - name: Get all servers
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ result.nitro_auth_token }}"
        validate_certs: no

        operation: get_all

        resource: "{{ resource }}"
