- hosts: citrix_adc
  gather_facts: no
  vars:
    resource: lbvserver
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6
  collections:
    - citrix.adc

  tasks:
    - name: Get filtered
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: get_filtered

        resource: "{{ resource }}"
        filter:
          ipv46: 10.8.0.1
