- hosts: mas
  gather_facts: no
  vars:
    resource: lbvserver
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6

  collections:
    - citrix.adc

  tasks:
    - name: Do mas login
      delegate_to: localhost
      register: login_result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: mas_login

    - name: Get all servers
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ login_result.nitro_auth_token }}"
        instance_ip: 10.78.60.202
        validate_certs: no

        operation: get_all

        resource: server

    - name: save config
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_auth_token: "{{ login_result.nitro_auth_token }}"
        instance_ip: 10.78.60.202

        operation: save_config
