
- hosts: citrix_adc
  gather_facts: no
  vars:
    resource: server
    attributes:
      name: test-server-1
      ipaddress: 192.168.1.6
  collections:
    - citrix.adc

  tasks:
    - name: Get resource
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        expected_nitro_errorcode: [0, 258]
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: rename

        resource: "{{ resource }}"
        attributes:
          newname: "{{ attributes.name }}"
          name: test-server-2
