- hosts: citrix_adc

  gather_facts: False
  vars_files:
    - workflows.yaml
  collections:
    - citrix.adc

  tasks:
    - name: Setup nitro resource lb group
      delegate_to: localhost
      citrix_adc_nitro_resource:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: absent

        workflow: "{{ workflow.lbgroup }}"

        resource:
          name: mylbgroup
          timeout: 150
