- hosts: citrix_adc
  gather_facts: no
  collections:
    - citrix.adc

  tasks:
    - name: Remove all databases. Make transaction count zero
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: action
        action: reset

        resource: appfwlearningdata 
        args:
          profilename: testprofile 
          securitycheck: starturl 
        attributes: {}
