- hosts: citrix_adc
  gather_facts: no
  collections:
    - citrix.adc

  tasks:
    - name: Export appfw learnt data in csv format to the location /var/learnt_data/
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: action
        action: export 

        resource: appfwlearningdata 

        attributes: 
          profilename: testprofile
          securitycheck: starturl
          target: test_starturl.csv # to be saved in NetScaler@./var/learnt_data/test_starturl.csv
