- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc


  tasks:
    - name: setup appfw conf id field
      delegate_to: localhost
      register: result
      citrix_adc_appfw_fieldtype:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        state: present
        validate_certs: no

        name: field_type_name
        regex: "reman"
        priority: "100"
        comment: field type comment
