- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc


  tasks:
    - name: Setup appfw policy
      delegate_to: localhost
      citrix_adc_appfw_policy:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: policy_test_2
        rule: 'HTTP.REQ.HOSTNAME.DOMAIN.EQ("blog.example.com")'
        profilename: APPFW_BLOCK
        comment: 'policy test comment'
