- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc


  tasks:
    - name: setup appfw json contenttype
      delegate_to: localhost
      register: result
      citrix_adc_appfw_jsoncontenttype:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        state: present
        validate_certs: no

        jsoncontenttypevalue: "some.*regex"
        isregex: "REGEX"
