- hosts: citrix_adc
  gather_facts: no
  vars:
    resource: appfwlearningdata 
  collections:
    - citrix.adc

  tasks:
    - name: Get the unreviewed appfw learningdata for the specified profile and security check 
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: get_by_args

        resource: "{{ resource }}"
        args:
          profilename: testprofile 
          securitycheck: starturl 
