- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc


  tasks:
    - name: setup appfw conf id field
      delegate_to: localhost
      register: result
      citrix_adc_appfw_confidfield:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no
        state: present

        fieldname: "field_name"
        url: "http://some.other.url"
        isregex: "REGEX"
        comment: Some comment
        disabled: no
