
- hosts: citrix_adm

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adm

  tasks:
    - name: Login to mas
      delegate_to: localhost
      register: login_result
      citrix_adm_login:
        mas_ip: "{{ mas_ip }}"
        mas_user: "{{ mas_user }}"
        mas_pass: "{{ mas_pass }}"

    - name: poll instances
      delegate_to: localhost
      citrix_adm_poll_instances:
        mas_ip: "{{ mas_ip }}"
        nitro_auth_token: "{{ login_result.session_id }}"
