---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Configure lb monitor for catalog
      delegate_to: localhost
      citrix_adc_lb_monitor:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        monitorname: monitor_catalog
        type: HTTP
        respcode: ['200']

    - name: Configure lb monitor for cart
      delegate_to: localhost
      citrix_adc_lb_monitor:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        monitorname: monitor_cart
        type: HTTP
        respcode: ['200']

    - name: Configure service group catalog
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        servicegroupname: service_group_catalog
        servicetype: HTTP
        servicemembers:
          mode: exact
          attributes:
            - ip: 10.78.78.78
              port: 80
              weight: 50
            - ip: 10.79.79.79
              port: 80
              weight: 50
        monitor_bindings:
          mode: exact
          attributes:
            - monitorname: monitor_catalog
              weight: 100

    - name: Configure service group cart
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        servicegroupname: service_group_cart
        servicetype: HTTP
        servicemembers:
          mode: exact
          attributes:
            - ip: 11.78.78.78
              port: 80
              weight: 50
            - ip: 11.79.79.79
              port: 80
              weight: 50
        monitor_bindings:
          mode: exact
          attributes:
            - monitorname: monitor_cart
              weight: 100

    - name: Configure lb vserver cart
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: lb_vserver_cart
        servicetype: HTTP
        ipv46: 10.8.0.1
        port: 80

    - name: Configure lb vserver catalog
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: lb_vserver_catalog
        servicetype: HTTP
        ipv46: 10.8.0.2
        port: 80


    - name: Configure catalog policy
      delegate_to: localhost
      citrix_adc_cs_policy:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        policyname: catalog_policy
        url: /catalog/*

    - name: Configure cart policy
      delegate_to: localhost
      citrix_adc_cs_policy:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        policyname: cart_policy
        url: /cart/*

    - name: Configure cs vserver
      delegate_to: localhost
      citrix_adc_cs_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: cs_vserver_1
        ipv46: 10.22.24.22
        port: 80
        servicetype: HTTP

        policybindings:
          - policyname: catalog_policy
            targetlbvserver: lb_vserver_catalog
          - policyname: cart_policy
            targetlbvserver: lb_vserver_cart
