---

- hosts: citrix_adc
  gather_facts: false
  collections:
    - citrix.adc

  tasks:
    - name: lb vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no


        name: lb-vserver-1
        servicetype: HTTP
        ipv46: 6.92.2.2
        port: 80

    - name: cs action
      delegate_to: localhost
      citrix_adc_cs_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        name: action1
        targetlbvserver: lb-vserver-1
