---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: 'SETUP cs_vserver_appfwpolicy_binding'
      delegate_to: localhost
      register: result
      citrix_adc_cs_vserver:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: present

        name: cs-vserver-appfw-policy
        port: 80
        ipv46: 10.79.1.3
        servicetype: HTTP
        appfw_policybindings:
          - priority: 100
            bindpoint: REQUEST
            policyname: policy_cs_vserver_integration_helper
            labelname: cs-vserver-appfw-policy
            gotopriorityexpression: 101
            invoke: true
            labeltype: reqvserver
            sc: off
