---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Set lb vserver 1
      delegate_to: localhost
      citrix_adc_lb_vserver: 
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: lbvserver_1
        servicetype: HTTP
        ipv46: 10.78.1.1
        port: 80


    - name: Set cs policy
      delegate_to: localhost
      citrix_adc_cs_policy: 
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        policyname: policy_1
        url: /example/


    - name: Set cs vserver
      delegate_to: localhost
      citrix_adc_cs_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: cs-vserver-1
        ipv46: 192.168.1.1
        port: 90
        servicetype: HTTP

        policybindings:
          - policyname: policy_1
            targetlbvserver: lbvserver_1
