- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: Setup gslb vserver
      delegate_to: localhost
      citrix_adc_gslb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        name: gslb-vserver-1
        servicetype: HTTP
