- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: Setup gslb service
      delegate_to: localhost
      citrix_adc_gslb_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        servicename: gslb-service-test
        servicetype: HTTP
        port: 80
        sitename: gslb-site-test
        ipaddress: 192.168.3.5
        healthmonitor: yes
