---

- hosts: citrix_adc

  gather_facts: False
  collections: citrix.adc

  tasks:

    - name: Set service 1
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        nitro_protocol: https
        validate_certs: no

        state: present

        name: server_2
        ipaddress: 10.80.0.1
