---

- hosts: citrix_adc

  vars:
    max_clients: 5
    state: present

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: ssl binding
      delegate_to: localhost
      citrix_adc_ssl_certkey:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: "{{ state }}"

        certkey: certificate_1
        cert: server.crt
        key: server.key

    - name: Set service 1
      delegate_to: localhost
      citrix_adc_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: "{{ state }}"

        name: service-http-1
        servicetype: SSL
        ip: 10.78.0.1
        ipaddress: 10.78.0.1
        port: 80

    - name: Set service 2
      delegate_to: localhost
      citrix_adc_service:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: "{{ state }}"

        name: service-http-2
        servicetype: SSL
        ip: 10.78.0.2
        ipaddress: 10.78.0.2
        port: 80

    - name: lb vserver 1
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: "{{ state }}"

        name: lb_vserver_1
        servicetype: SSL
        timeout: 2
        ipv46: 6.93.3.3
        port: 80
        servicebindings:
            -
                servicename: service-http-1
                weight: 80
            -
                servicename: service-http-2
                weight: 20
