---

- hosts: citrix_adc

  vars:
    max_clients: 5
    state: absent

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: 'SETUP lb_vserver_appfwpolicy_binding'
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        nsip: '{{ nsip }}'
        validate_certs: no

        state: present

        name: lb-vserver-appfw-policy
        port: 80
        ipv46: 10.79.1.3
        servicetype: HTTP
        appfw_policybindings:
          - priority: 100
            bindpoint: REQUEST
            policyname: policy_lb_vserver_integration_helper
            labelname: lb-vserver-appfw-policy
            gotopriorityexpression: 101
            invoke: true
            labeltype: reqvserver
