- hosts: mas

  vars:
    max_clients: 5
  gather_facts: False
  collections:
    - citrix.adc

  tasks:

    - name: Get MAS authentication token
      delegate_to: localhost
      citrix_adc_nitro_request:
        mas_ip: "{{ nsip }}"
        mas_user: "{{ nitro_user }}"
        mas_pass: "{{ nitro_pass }}"
        validate_certs: no

        operation: mas_login

      register: mas_login_result


    - name: Setup server through MAS proxy
      delegate_to: localhost
      citrix_adc_server:
        mas_ip: "{{ nsip }}"
        mas_auth_token: "{{ mas_login_result.nitro_auth_token }}"
        mas_proxy_call: true
        validate_certs: no
        instance_ip: "{{ instance_ip }}"

        state: present


        name: test-server-1
        ipaddress: 192.168.2.2
        disabled: yes
        graceful: yes
