---
- hosts: citrix_adc

  vars:
    save_config: no
    state: present

  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Set server 1
      delegate_to: localhost
      notify: save config
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        save_config: "{{ save_config }}"

        state: "{{ state }}"
        name: server-1
        ipaddress: 192.168.1.1

    - name: Set server 2
      delegate_to: localhost
      notify: save config
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        save_config: "{{ save_config }}"

        state: "{{ state }}"
        name: server-2
        ipaddress: 192.168.1.2

  handlers:
    - name: save config
      delegate_to: localhost
      citrix_adc_save_config:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
