---
- hosts: citrix_adc

  vars:
    max_clients: 5
  collections:
    - citrix.adc


  remote_user: root
  gather_facts: False

  tasks:
    - name: Set server 1
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present
        name: server-1
        ipaddress: 10.11.11.12

    - name: Set server 2
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present
        name: server-2
        ipaddress: 10.11.11.13

    - name: Set service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: service-group-1
        servicetype: HTTP
        clttimeout: 300
        servicemembers:
          mode: exact
          attributes:
            - servername: server-1
              port: 8080
              weight: 50
