---

- hosts: citrix_adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Set ssl certificate key
      delegate_to: localhost
      citrix_adc_ssl_certkey:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        certkey: certificate_1
        cert: server.crt
        key: server.key
        password: yes
        passplain: nosecret
        expirymonitor: enabled
        notificationperiod: 50
        inform: PEM

    - name: Set ssl certificate key 2
      citrix_adc_ssl_certkey:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"

        state: present

        certkey: certificate_2
        cert: server2.crt
        key: server2.key
      delegate_to: 127.0.0.1
