---
- hosts: citrix_adc
  connection: citrix.adc.ssh_citrix_adc
  remote_user: nsroot
  gather_facts: false

  vars:
    ansible_python_interpreter: /var/python/bin/python

  tasks:
    - name: Calling shell module
      shell: "echo hello"
      register: echo_result

    - name: Show command output
      debug:
        msg: "{{ echo_result }}"
