---
- hosts: citrix_adc
  connection: citrix.adc.ssh_citrix_adc
  remote_user: nsroot
  gather_facts: false

  vars:
    ansible_python_interpreter: /var/python/bin/python

  tasks:
    - name: Calling shell module
      shell: "echo hello"
      register: echo_result

    - name: Show command output
      debug:
        msg: "{{ echo_result }}"

- hosts: citrix_adc
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Setup server
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        name: test-server-1
        ipaddress: 192.168.2.2
