---
- hosts: citrix_adc

  vars:
    max_clients: 5

  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: Set service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present
        disabled: no

        servicegroupname: service-group-1
        servicetype: HTTP
        servicemembers:
          mode: exact
          attributes:
            - ip: 192.168.10.1
              port: 80
              weight: 60
            - ip: 192.168.10.2
              port: 80
              weight: 40
