name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        virtualenv -p /usr/bin/python3 virtualenvironment
        source virtualenvironment/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.test.txt
        python install.py
    - name: Test with pylint
      run: |
        pip install pylint
        pylint ansible-modules/*
