name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.test.txt
        pip install pylint
        python install.py
    - name: Test Citrix ADC ansible modules with pylint
      run: |
        pylint -E ansible-modules/citrix_adc_*.py
    - name: Test Citrix ADM ansible modules with pylint
      run: |
        pylint -E ansible-modules/citrix_adm_*.py
